### ISSUE TITLE
Empty wishlist returns 400 error

### ISSUE THREAD

**Issue by simplenotezy** [TemplateInvaders/ti-woocommerce-wishlist#23]
When you request a wishlist, but it is empty, an error 400 is returned, and this is not expected. It should be 200 with an empty array. Otherwise requests will fail, and the error handler will be used, instead of the success handler.

**Comment by doozy** [comment]
Fixed in 1.17.0 version

**Comment by simplenotezy** [comment]
Hi @doozy - this issue has not been fixed.  I am running version 1.17.1 and I still get this error

**Comment by simplenotezy** [comment]
Have a look: https://staging.thejewelleryroom.com/wp-json/wc/v3/wishlist/A6DF7B/get_products?lang=da&count=100

**Comment by simplenotezy** [comment]
Oh wait, staging server wasn't deployed properly. The issue has been fixed. Thanks!
